# 用于各项接口替换规则

# 主要接口
__ALLHISTORY_HOSTNAME__ : //10.4.40.168:8443

# 图片服务地址
__ALLHISTORY_IMAGEHOST__ : //pic.evatlas.com

# 地图瓦片服务地址
__ALLHISTORY_MAPTILEHOST__ : //maptile.allhistory.com

# 地图接口服务地址
__ALLHISTORY_MAPHOST__ : http://mapre.allhistory.com

# 测试环境域名地址
__ALLHISTORY_LOCATION_HOSTNAME__ : http://10.4.40.168:3000

